theme: jekyll-theme-architect

title: [Java EE Security API (JSR-375)]
description: [Repository for JSR-375 API Code]

# sidebar links url
links:
  source: https://github.com/javaee/security-api
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

